### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by mzergi** [BME-MIT-IET/iet-hf2021-todo-team-name#3]
Create unit tests to ensure the logic is working as intended

**Comment by MrPatesz** [comment]
Created new branch for this issue

**Comment by MrPatesz** [comment]
Created an xUnit Test Project
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/920f5514de8a014567d77925a745d6c48802d728

**Comment by MrPatesz** [comment]
Modified Controllers to take Interfaces of the Repositories
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/a1f17073615685e98f95b9d4ed9ee8efdf2b9308

**Comment by MrPatesz** [comment]
Created FakeLabelRepository for testing
Created the first test case: LabelController GET endpoint returns appropriate number of records
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/ed7f521139869858e8cee609097c29128f44b997

**Comment by MrPatesz** [comment]
LabelController fully tested, works correctly
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/aaeba73826188b232c81e813ee5474e4a44b6613

**Comment by MrPatesz** [comment]
Created FakeIssueRepository for testing
Created the first test case: testing whether IssueController's GET endpoint returns appropriate number of records or not
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/7013124564e618bb85d18e1033648759f677c78e

**Comment by MrPatesz** [comment]
IssueController fully tested, found some issues ;)
GetById returns a value even when the provided ID is unknown
Update's behaviour is questionable too
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/3769569e9eae8749b030c91aee8233e0a24b4f10

**Comment by mzergi** [comment]
Start working on unit tests for WorkspaceRepository and ClassRepository

**Comment by mzergi** [comment]
Started on working on unit tests and fake repository for ColumnRepository as it is needed for testing WorkspaceRepository

**Comment by mzergi** [comment]
ClassController fully tested, found some issues.
Dangerous functions should throw exceptions.

https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/657229a432ac48ba8a749a7192f1a40d0034c2c8

**Comment by MrPatesz** [comment]
IssueRepository's bugs fixed:
    GetIssue returns null when ID is unknown
    UpdateIssue doesn't add new item when ID is unknown
DeleteClass renamed to DeleteIssue (probably ctrl+c error)
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/23f1565e59e9c8811ef78d4a61b10b0e4a890c1a

**Comment by MrPatesz** [comment]
During testing I found that userID is rarely tested for modifying methods
It's only used for query methods
This is a big security problem
As long as I'm logged in I could delete any resource that has an ID that I'm aware of

**Comment by mzergi** [comment]
Finished with planned tests for ColumnController, ran code coverage analysis.
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/dd69cc6219396774609b52a6e12b38f31b4592dd

**Comment by MrPatesz** [comment]
Finalized documentation
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/b38fa1e2307b0bfc65bb248b1c3775433863af85

**Comment by MrPatesz** [comment]
Updated documentation, fixed typos and grammar errors.
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/31073818e0eb915d73ed914a95d0026a7582c011

**Comment by MrPatesz** [comment]
Tests for modifying other user's Issue
https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/commit/e3ffd0184c71318446c848565b4dc89434952159

**Comment by npatrik** [comment]
Reviewed. Suggested changes.
